settings:
  title: 'État des services'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo.webp # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Tous les systèmes sont opérationnels'
  notAllmonitorsOperational: 'Tous les systèmes ne sont pas opérationnels'
  monitorLabelOperational: 'Opérationnel'
  monitorLabelNotOperational: 'Non opérationnel'
  monitorLabelNoData: 'Pas de données'
  dayInHistogramNoData: 'Aucune donnée'
  dayInHistogramOperational: 'En ligne'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: picxly
    name: Picxly
    description: 'Site internet'
    url: 'https://picxly.pw/'
    method: GET
    expectStatus: 200

  - id: cdn
    name: Plume
    description: 'Stockage'
    url: 'https://picxly.pw/'
    method: GET
    expectStatus: 200
